### ISSUE TITLE
Asciidoctor-pdf / Docbook XSL styling

### ISSUE THREAD

**Issue by jachiang** [merklebloom/bookbuilder#3]
Quick question regarding rebuild to use Asciidoctor-pdf tool to build for PDF/FOP outputs.

How do you plan to keep the styling sheets consistent across html/FOP?

- PDF/FOP: Asciidoctor-pdf has a .yml styling sheets.
- HTML/Ebook: Docbook toolchain uses XML styling sheets.

I generally struggling to consolidate the two. Asciidoctor-pdf offers little control (e.g. where to render footnotes), and Docbook toolchain ... is pretty complex.

**Comment by aantonop** [comment]
I've transitioned both format to "native" Ruby toolchains via asciidoctor. XML has now been deprecated. The PDF output uses the .yml styling sheets and the ebook uses CSS. 

It is not possible to consolidate the styling, nor is it really desirable - ebook readers operate in an entirely different way than typeset documents (PDF). Ebook content is reflowable (responsive), whereas PDF is paginated in a very rigid way. 

Have a look at the newly updated repository - the docker container makes it easier across platforms and the documentation has been updated.
